// libreria que nos permitira conectarse a mongodb
//https://backendtiendavirtual.onrender.com/api/listCompanies
const mongoose = require("mongoose");
const { Schema } = mongoose;

// const noteSchema = new Schema({
//   title: { type: String, required: false },
//   paragraph:{type:String,required:false}
// }) COMO ESET MODELO ES DINAMICO YA QUE LOS CAMPOS VARIAN SEGUN EL DATO ENVIADO ENTONCES SE DEJA EL SCHEMMA
//VACIO DE LA SIGUIENTE MANERA

const noteSchema = new Schema({
  title1: String,
  title2: String,
  title3: String,
  title4: String,
  title5: String,
  title6: String,
  title7: String,
  title8: String,
  title9: String,
  title10: String,
  paragraph1: String,
  paragraph2: String,
  paragraph3: String,
  paragraph4: String,
  paragraph5: String,
  paragraph6: String,
  paragraph7: String,
  paragraph8: String,
  paragraph9: String,
  paragraph10: String,
  paragraph11: String,
  paragraph12: String,
  paragraph13: String,
  paragraph14: String,
  paragraph15: String,
  paragraph16: String,
  paragraph17: String,
  paragraph18: String,
  paragraph19: String,
  paragraph20: String,
  paragraph21: String,
  paragraph22: String,
  paragraph23: String,
  paragraph24: String,
  paragraph25: String,
  paragraph26: String,
  paragraph27: String,
  paragraph28: String,
  paragraph29: String,
  paragraph30: String,
  paragraph31: String,
  paragraph32: String,
  paragraph33: String,
  paragraph34: String,
  paragraph35: String,
  paragraph36: String,
  paragraph37: String,
  paragraph38: String,
  paragraph39: String,
  paragraph40: String,
  paragraph41: String,
  paragraph42: String,
  paragraph43: String,
  paragraph44: String,
  paragraph45: String,
  paragraph46: String,
  paragraph47: String,
  paragraph48: String,
  paragraph49: String,
  paragraph50: String,
  list1: { type: String, require: false },
  list2: { type: String, require: false },
  list3: { type: String, require: false },
  list4: { type: String, require: false },
  list5: { type: String, require: false },
  list6: { type: String, require: false },
  list7: { type: String, require: false },
  list8: { type: String, require: false },
  list9: { type: String, require: false },
  list10: { type: String, require: false },
  list11: { type: String, require: false },
  list12: { type: String, require: false },
  list13: { type: String, require: false },
  list14: { type: String, require: false },
  list15: { type: String, require: false },
  list16: { type: String, require: false },
  list17: { type: String, require: false },
  list18: { type: String, require: false },
  list19: { type: String, require: false },
  list20: { type: String, require: false },
  list21: { type: String, require: false },
  list22: { type: String, require: false },
  list23: { type: String, require: false },
  list24: { type: String, require: false },
  list25: { type: String, require: false },
  list26: { type: String, require: false },
  list27: { type: String, require: false },
  list28: { type: String, require: false },
  list29: { type: String, require: false },
  list30: { type: String, require: false },
  list31: { type: String, require: false },
  list32: { type: String, require: false },
  list33: { type: String, require: false },
  list34: { type: String, require: false },
  list35: { type: String, require: false },
  list36: { type: String, require: false },
  list37: { type: String, require: false },
  list38: { type: String, require: false },
  list39: { type: String, require: false },
  list40: { type: String, require: false },
  list41: { type: String, require: false },
  list42: { type: String, require: false },
  list43: { type: String, require: false },
  list44: { type: String, require: false },
  list45: { type: String, require: false },
  list46: { type: String, require: false },
  list47: { type: String, require: false },
  list48: { type: String, require: false },
  list49: { type: String, require: false },
  list50: { type: String, require: false },
  list51: { type: String, require: false },
  list52: { type: String, require: false },
  list53: { type: String, require: false },
  list54: { type: String, require: false },
  list55: { type: String, require: false },
  list56: { type: String, require: false },
  list57: { type: String, require: false },
  list58: { type: String, require: false },
  list59: { type: String, require: false },
  list60: { type: String, require: false },
  list61: { type: String, require: false },
  list62: { type: String, require: false },
  list63: { type: String, require: false },
  list64: { type: String, require: false },
  list65: { type: String, require: false },
  img1: String,
  img2: String,
  img3: String,
  img4: String,
  img5: String,
  img6: String,
  img7: String,
  image: String,
  avatar: { type: String, required: false },
  typeNote: String,
});

module.exports = mongoose.model("Note", noteSchema);
